<?php

namespace Zadorin\Airtable\Errors;

/**
 * Base class for internal errors generated by package itself.
 * Validation, logic erros, etc.
 */
abstract class PackageError extends AirtableError
{

}
